version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore autometricsai-backend.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output autometricsai-backend.csproj
      - echo replace env variable inside appsettings json
      - sed -i 's/ENVIRONMENT_VALUE/$ENVIRONMENT/g' appsettings.json
artifacts:
  files:
    - ./**/*
  base-directory: './build_output'