version: 0.2
phases:
  pre_build:
    commands:
      - echo replace env variable inside appsettings json
      - echo $ENVIRONMENT
      - sed -i "s/ENVIRONMENT_VALUE/$ENVIRONMENT/g" appsettings.json
      - echo Restore started on `date`
      - dotnet restore autometricsai-backend.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output autometricsai-backend.csproj
      - zip autometricsai-backend.zip -r ./build_output
      - aws s3 cp --sse aws:kms --sse-kms-key-id "arn:aws:kms:ap-southeast-2:444601120704:key/a9f43b19-4f29-42ae-bc24-6bb6fda0eeac" autometricsai-backend.zip s3://$PACKAGE_BUCKET_NAME
artifacts:
  files:
    - ./**/*
  base-directory: './build_output'